/* Generated by Cython 0.27.3 */

#ifndef __PYX_HAVE__lib__utils__bbox
#define __PYX_HAVE__lib__utils__bbox


#ifndef __PYX_HAVE_API__lib__utils__bbox

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyArrayObject *bbox_overlaps(PyArrayObject *, PyArrayObject *, int __pyx_skip_dispatch);
__PYX_EXTERN_C PyArrayObject *bbox_intersections(PyArrayObject *, PyArrayObject *, int __pyx_skip_dispatch);

#endif /* !__PYX_HAVE_API__lib__utils__bbox */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initbbox(void);
#else
PyMODINIT_FUNC PyInit_bbox(void);
#endif

#endif /* !__PYX_HAVE__lib__utils__bbox */
