/* Generated by Cython 0.26 */

#ifndef __PYX_HAVE__lib__utils__cython_nms
#define __PYX_HAVE__lib__utils__cython_nms


#ifndef __PYX_HAVE_API__lib__utils__cython_nms

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *nms(PyArrayObject *, PyObject *, int __pyx_skip_dispatch);

#endif /* !__PYX_HAVE_API__lib__utils__cython_nms */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initcython_nms(void);
#else
PyMODINIT_FUNC PyInit_cython_nms(void);
#endif

#endif /* !__PYX_HAVE__lib__utils__cython_nms */
